version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/usr/share/nginx/html:ro
    
  app:
    image: my-backend-image:latest
    build: .
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongodb
    env_file:
      - .env 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - db-data:/data/db
    env_file:
      - .env 

volumes:
  db-data:

networks:
  app-network:
    driver: bridge